<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Date of Birth input field</description>
   <name>dtp_DateOfBirth</name>
   <tag></tag>
   <elementGuidId>eb33a35e-bfc5-4aff-8cdd-95488af1b6ef</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dob</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
