name: Katalon Test Execution

on:
  push:
    branches:
      - master
  schedule:
    - cron: '10 11 * * *'    # Daily at 4:40 PM IST
  workflow_dispatch:

jobs:
  katalon-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Katalon Tests
        uses: katalon-studio/katalon-runner@v1
        with:
          version: '10.0.0'
          projectPath: ${{ github.workspace }}
          testSuitePath: 'Test Suites/TS1'
          executionProfile: 'default'
          browserType: 'Chrome'
          apiKey: ${{ secrets.KATALON_API_KEY }
